// no sorting yet just going off what I can recall from the dome 

export const produce_list = [
    'Romaine Crunch',
    'Baby Spinach',
    'Baby Arugula',
    '50_50 Mix',
    'Organic Spring Mix',
    'Organic XL Spring Mix',
    'Lemon Herb',
    'Sweet Kale',
    'Basil Crunch',
    'Caesar',
    'Spring Blush',
    'Romaine Hearts',
    'Red Bell Pepper',
    'Green Bell Pepper',
    'Yellow Bell Pepper',
    'Purple Bell Pepper', // super rare
    'Snap Peas',
    'Bulk Green Beans',
    'Bag Green Beans',
    'Bulk Cucumber',
    'Bulk Zucchini',
    'Bulk Shiitake Mushrooms',
    'Bulk Crimini Mushrooms', // i HATE these they smell like actually ass 
    'Bulk Portabella Mushrooms',
    'Celery',
    'Asparagus',
    'Green Kale',
    'Red Kale',
    'Lacinto Kale',
    'Green Lettuce',
    'Red Lettuce',
    'Romaine Lettuce',
    'Bok Choi',
    'Red Chard',
    'Cilantro',
    'Parsley',
    'Lemons',
    'Limes',
    'Honeycrisp Apples',
    'Fuji Apples',
    'Cosmic Crisp Apples',
    'Pink Lady Apples',
    'Bag Pink Lady Apples',
    'White Peaches',
    'Colorado Peaches',
    'Yellow Nectarines',
    'White Nectarines',
    'Red Plums',
    'Black Plums',
    'Beefsteak Tomatoes',
    'Roma Tomatoes',
    'Vine-on Tomatoes',
    'Heirloom Tomatoes',
    'Cherry Tomatoes',
    'Grape Tomatoes',
    'Bulk Basil',
    'Ataulfo Pears',
    "d'Anjou Pears",
];